<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Transaction Generation</title>
    <style>
        
        .rightText{
            text-align: right;
        }
        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 0.5px solid #000;
            padding: 8px;
        }
        .content {
            margin-bottom: 50px;
        }
        table.signatories-table th, table.signatories-table td {
            border: none;
        }
        table.date-generated th, table.date-generated td {
            border: none;
        }
        body{
            font-size: 12px;
        }
        .header {
            text-align: center;
            padding-bottom: 10px;
            font-size: 14px;
            position: absolute;
            top: 0px; /* Space between the header and top of the page */
            left: 0;
            right: 0;
        }

        /* Footer style */
        * Footer style */
        .footer {
            position: fixed;
            bottom: 30px; /* Distance from the bottom of the page */
            left: 0;
            right: 0;
            text-align: center;
            font-size: 9px;
            padding-top: 10px;
        }
        .footer .left {
            text-align: left; /* Ensures the "Generated By" is on the left */
        }

        .footer .right {
            text-align: right; /* Ensures the page number is on the right */
        }
        /* Page number style */
        .pagenum:before {
            content: counter(page);
        }

        /* Hide header on all pages except first page */
        .first-page-header {
            display: block;
        }

        .not-first-page .first-page-header {
            display: none;
        }

    </style>
</head>
<body>
<div class="header first-page-header">
    <table style="border: none; border-collapse: collapse;">
        <tbody>
            <tr>
                <th style="border: none;">
                    <img style="width: 100px; height: 100px; margin: 0 auto; margin-left: 40rem" src="{{ $logoPh }}">
                </th>
                <td style="text-align: center; border: none;" width="80%">
                    <p style="margin: 0; font-weight: bold; font-size: 20px; font-family: 'Garamond', serif;">Republic of the Philippines</p>
                    <p style="margin: 0; font-weight: none">Province of Nueva Vizcaya</p>
                    <p style="margin: 0; font-weight: none">Bayombong</p>
                    <span style="margin: 0; font-size: 13px; font-weight:bold">PROVINCIAL HUMAN RESOURCE AND MANAGEMENT OFFICE</span>
                    <p style="margin: 0; font-size: 18px; font-weight:bold; margin-top:0.5rem;">Transaction Records</p>
                </td>
                <th style="border: none;">
                    <img style="width: 80px; height: 80px; margin: 0 auto; margin-right: 39rem" src="{{ $logo }}">
                </th>
            </tr>
        </tbody>
    </table>    
</div>
<main style="margin-top: 9rem">
    <div class="container-fluid">
        <table class="table" style="font-size: 10px">
            <thead>
                <tr>
                    <th>Time Request</th>
                    <th>Transaction Number</th>
                    <th>Stock On Hand</th>
                    <th>Quantity</th>
                    <th>UoM</th>
                    <th>Item Name</th>
                    <th>Requestor</th>
                    <th>Date/Time Acted</th>
                    <th>Request Aging</th>
                    <th>Released by</th>
                    <th>Time Released</th>
                    <th>Availability Aging</th>
                    <th>Remarks</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($transactions as $transaction)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($transaction->created_at)->format('F d, Y h:i A') }}</td>
                        <td>{{ $transaction->transaction_number }}</td>
                        <td>{{ $transaction->item->inventory->quantity }}</td>
                        <td>{{ $transaction->transactionDetail->request_quantity }}</td>
                        <td>{{ $transaction->item->inventory->unit->name }}</td>
                        <td>{{ $transaction->item->name }}</td>
                        <td>{{ $transaction->client ? $transaction->client->full_name : $transaction->admin->full_name }}</td>
                        <td>
                            {{ $transaction->approved_date ? \Carbon\Carbon::parse($transaction->approved_date)->format('F d, Y') : '--' }}
                            {{ $transaction->approved_time ? \Carbon\Carbon::parse($transaction->approved_time)->format('h:i A') : '--' }}
                        </td>
                        
                        <td>{{ $transaction->request_aging ? $transaction->request_aging : '--' }}</td>
                        <td>{{ $transaction->adminBy ? $transaction->adminBy->full_name : '--' }}</td>
                        <td>{{ $transaction->released_time ? \Carbon\Carbon::parse($transaction->released_time)->format('h:i A') : '--' }}</td>
                        <td>{{ $transaction->released_aging }}{{ $transaction->released_aging ? $transaction->released_aging : '--' }}</td>
                        <td>{{ $transaction->remark }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <table class="signatories-table table" style="border: none;">
                    <thead class="signatories-table">
                        <tr>
                            <td colspan="2">Prepared by:</td>
                            <td colspan="2">Reviewed by:</td>
                            <td colspan="2">Noted by:</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td colspan="2">
                                <p>
                                    <strong>{{ strToUpper($preparedBy->full_name) }}</strong><br>
                                    <span style="font-style: italic">{{ $preparedBy->position }}</span>
                                </p>
                            </td>
                            <td colspan="2">
                                <p>
                                    <strong>CHRISTINE JOY C. BARTOLOME</strong><br>
                                    <span style="font-style: italic">AAIV/ACTING AO</span>
                                </p>
                            </td>
                            <td colspan="2">
                                <p>
                                    <strong>MA. CARLA LUCIA M. TORRALBA</strong><br>
                                    <span style="font-style: italic">PHRMO</span>
                                </p>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</main>
<div class="footer">
    <div class="left">
        <span>Generated By: {{ $generatedBy->full_name }} | Date/Time Generated: {{ $now }}</span>
    </div>
    <div class="right">
        <span>Page <span class="pagenum"></span></span>
    </div>
</div>
</body>
</html>