@extends('admin.layout.admin-layout')
@section('content')
<div class="container-fluid mt-3">
    <div class="row">
        <div class="col-md-9" style="text-align: left">
            <h4><strong>QUARTERLY REPORTS</strong></h4>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <table id="reportsTable" class="table-striped table-hover" style="font-size: 12px">
                <thead style="background-color: #3d5c99; color:white">
                    <tr>
                        <th width="12%">Date/Time Generated</th>
                        <th width="10%">Report Number</th>
                        <th width="10%">Generated By</th>
                        <th width="10%">Position</th>
                        <th width="5%">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($reports as $report)
                        @if ($report->report_type != "Monthly")
                            <tr>
                                <td>{{ \Carbon\Carbon::parse($report->created_at)->format('F d, Y H:i A') }}</td>
                                <td>{{ $report->control_number }}</td>
                                <td>{{ $report->admin->full_name }}</td>
                                <td>{{ $report->admin->position }}</td>
                                <td class="text-center">
                                    <button class="btn btn-info view-pdf-btn" style="font-size: 0.75rem; padding: 0.25rem 0.5rem;" data-filename="{{ $report->report_file }}"><i class="fa fa-eye"></i></button>
                                </td>
                            </tr> 
                        @endif
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="pdfPreviewModal" tabindex="-1" role="dialog" aria-labelledby="pdfModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-fullscreen" role="document"> <!-- Use this for Bootstrap 5 -->
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="pdfModalLabel">PDF Preview</h5>
                <button type="button" class="close btn btn-danger" id="pdf-preview-close-btn" data-dismiss="modal" aria-label="Close">
                    <span>&times;</span>
                </button>
            </div>
            <div class="modal-body p-0"> <!-- Remove padding -->
                <iframe id="pdfFrame" src="" width="100%" height="100%" style="border: none;"></iframe>
            </div>
        </div>
    </div>
</div>
@endsection
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{{ asset('assets/js/admin/report/add-report.js') }}"></script>